### PR TITLE
[WIP] Create/Update/Build generalization

### PR DESCRIPTION
**Pull request by Mogball**
We can figure out merging later

### CODE REVIEW

**Comment by dhillondeep** [comment]
So far only `pkg` command is implemented. One thing I notice is that if framework and platform are set to `all`, then the default target will use `all` value as well (which does not work). How do we decide a default target? I would say just create a native target

**Comment by Mogball** [comment]
@dhillondeep  ready for review I guess

App, Pkg, build, clean, run, etc. are stable,

There seems to be some issues with package commands (a package.json isn't being generated) but that can be fixed later

**Comment by Mogball** [comment]
fixed issues with package commands, is probably stable enough for a merge (obviously not release)

test suite to follow?

**Comment by dhillondeep** [comment]
Just saw this now. I was thinking we should merge this into development branch instead of master. We will then merge development into master when we are ready for release. This way we can still do hotfixes for the current release. What do you say about that @Mogball ?

**Comment by Mogball** [comment]
Master already has a bunch of commits that aren't related to release. And we can't republish the same version (i.e. on npm and such). So we can just merge into master or whatever and when we release just give it a tag

**Pull request merged**
